version: "3.5"

services:
  redis:
    image: redis
    container_name: backend_cache
    restart: unless-stopped

  backend:
    image: go-project # Has to be built through a dockerfile previously or use a username/repository
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=backend_cache


  frontend:
    image: node-frontend # Has to be built through a dockerfile previously or use a username/repository
    container_name: react
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080



