FROM golang:alpine
EXPOSE 8080
ENV REQUEST_ORIGIN http://localhost:5000
# Must have a workdir set up, otherwise you might get this "$GOPATH/go.mod exists but should not"
WORKDIR /app
COPY . .

RUN go build \
    && adduser -D NON_ROOT_USER

USER NON_ROOT_USER

CMD ["./server"]